sudo: false
os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - '4'
  - '6'
  - '8'
  - '10'
  - '12'
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov --disable=gcov -f .nyc_output/*.json
